1.  Display employee name, department name, and salary.
A.  select e.emp_name,d.dept_name,e.salary
	from employees e 
	join departments d
	on e.dept_id = d.dept_id

2.  Show all departments and the number of employees in each department.
A.	select d.dept_name,count(e.emp_id) as employee_count
	from departments d
	left join employees e
	on d.dept_id = e.dept_id
	group by d.dept_id,d.dept_name

3.  Find employees along with their manager names.
A.	select e.emp_id,e.emp_name, e1.emp_name as manager_name
	from employees e
	left join employees e1
	on e.manager_id = e1.emp_id

4.  Find the total salary expenditure for each department.
A.	select d.dept_name,sum(e.salary)as total_salary
	from departments d
	left join employees e
	on d.dept_id = e.dept_id
	group by d.dept_id,d.dept_name

5.  Find the average salary for each department.
A.	select d.dept_name,avg(e.salary)as avg_salary
	from departments d
	left join employees e
	on d.dept_id = e.dept_id
	group by d.dept_id,d.dept_name

6.  Find the department with the highest average salary.
A.	select d.dept_name,avg(e.salary)as avg_salary
	from departments d
	left join employees e
	on d.dept_id = e.dept_id
	group by d.dept_id,d.dept_name
	order by avg_salary desc
	limit 1

7.  Find employees earning more than the company average salary.
A.	select emp_id,emp_name,salary
	from employees
	where salary>(select Avg(salary) from employees)

8.  Find employees earning more than their department average salary.
A.	select emp_id,emp_name,dept_id,salary
	from employees e
	where salary >(
	    select avg(salary)
	    from employees
	    where dept_id = e.dept_id)

9.  Find the second highest salary in the company.
A.	select salary
	from employees
	where salary <(
	  select max(salary)
	  from employees)
	order by salary desc
	limit 1

10. Find employees who earn the maximum salary in their department.
A.	select emp_id,emp_name,dept_id,salary
	from employees e
	where salary =(
	    select max(salary)
	    from employees
	    where dept_id = e.dept_id)

11. Rank employees based on salary within each department.
A.	select emp_id,emp_name,dept_id,salary,
	rank() over( partition by dept_id order by salary desc)as salary_rank
	from employees

12. Find the top 3 highest-paid employees in each department.
A.	select *
	from (
		select emp_id,emp_name,dept_id,salary,
		rank() over( partition by dept_id order by salary desc)as salary_rank
		from employees
	  )x
	where salary_rank <=3

13. Calculate running total salary ordered by hire date.
A.	select emp_id,emp_name,hire_date,salary,
	sum(salary) over(order by hire_date)as running_total_salary
	from employees

14. Show previous employee salary using LAG().
A.	select emp_id,emp_name,salary,
	LAG(salary) over (order by salary)as previous_salary
	from employees

15. Find customers who never placed an order.
A.	select c.customer_id,c.customer_name
	from customers c
	left join orders o
	on c.customer_id = o.customer_id
	where c.customer_id not in (select customer_id from orders)

16. Find the latest order for each customer.
A.	select customer_id,order_id
	from orders o
	where order_date = (select max(order_date)
	                    from orders
	                    where customer_id = o.customer_id)

17. Find total sales generated by each customer.
A.	select customer_id,sum(amount)
	from orders
	group by customer_id

18. Calculate customer contribution percentage to overall sales.
A.	select customer_id,sum(amount)*100/(select sum(amount) from orders) as customer_cuntribution
	from orders
	group by customer_id

19. Identify duplicate customer names.
A.	select customer_name
	from customers
	group by customer_name
	having count(*)>1

20. Classify employees into salary bands:
	Salary < 80,000        = Low
	80,000 - 120,000      = Medium
	Above 120,000         = High
	Display:
	Employee_Name
	Salary
	Salary_Band
A.	select emp_name,salary,
	case when salary <80000 then 'Low'
		 when salary between 80000 and 120000 then 'Medium'
	     else 'High'
	end as salary_brand
	from employees

21. Find employees having the same salary.
A.	select emp_id,emp_name,salary
	from employees
	where salary in(
	  select salary 
	  from employees
	  group by salary
	  having count(*)>1
	  )

22. Find customers who placed more than 3 orders.
A.	select c.customer_id,c.customer_name
	from customers c
	left join orders o
	on c.customer_id = o.customer_id
	group by c.customer_id, c.customer_name
	having count(*)>3

23. Find the month with highest sales.
A.	select month(order_date) as month_num,sum(amount)
	from orders
	group by month(order_date)
	order by sum(amount) desc
	limit 1

24. Calculate days between consecutive orders for each customer.
A.	select customer_id,order_date,
	lag(order_date) over(partition by customer_id order by order_date) as previous_date,
	datediff(order_date,lag(order_date) over(partition by customer_id order by order_date)
	         )as days_differnce
	from orders

25. Find departments where no employee was hired in the last 2 years.
A.  select d.dept_name 
	from departments d 
	join employees e 
	on d.dept_id=e.dept_id 
	group by d.dept_name 
	having MAX(hire_date) < current_date - interval 2 YEAR; 
